package sunxl8.your_diary.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sunxl8.your_diary.db.entity.ItemEntity;

import sunxl8.your_diary.db.dao.ItemEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemEntityDaoConfig;

    private final ItemEntityDao itemEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemEntityDaoConfig = daoConfigMap.get(ItemEntityDao.class).clone();
        itemEntityDaoConfig.initIdentityScope(type);

        itemEntityDao = new ItemEntityDao(itemEntityDaoConfig, this);

        registerDao(ItemEntity.class, itemEntityDao);
    }
    
    public void clear() {
        itemEntityDaoConfig.clearIdentityScope();
    }

    public ItemEntityDao getItemEntityDao() {
        return itemEntityDao;
    }

}
