package sunxl8.your_diary.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import sunxl8.your_diary.db.entity.TagEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TAG_ENTITY".
*/
public class TagEntityDao extends AbstractDao<TagEntity, Long> {

    public static final String TABLENAME = "TAG_ENTITY";

    /**
     * Properties of entity TagEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdItem = new Property(1, Long.class, "idItem", false, "ID_ITEM");
        public final static Property IdDiary = new Property(2, Long.class, "idDiary", false, "ID_DIARY");
        public final static Property Tag = new Property(3, String.class, "tag", false, "TAG");
    }


    public TagEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TagEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAG_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_ITEM\" INTEGER," + // 1: idItem
                "\"ID_DIARY\" INTEGER," + // 2: idDiary
                "\"TAG\" TEXT);"); // 3: tag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAG_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TagEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idItem = entity.getIdItem();
        if (idItem != null) {
            stmt.bindLong(2, idItem);
        }
 
        Long idDiary = entity.getIdDiary();
        if (idDiary != null) {
            stmt.bindLong(3, idDiary);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(4, tag);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TagEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idItem = entity.getIdItem();
        if (idItem != null) {
            stmt.bindLong(2, idItem);
        }
 
        Long idDiary = entity.getIdDiary();
        if (idDiary != null) {
            stmt.bindLong(3, idDiary);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(4, tag);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TagEntity readEntity(Cursor cursor, int offset) {
        TagEntity entity = new TagEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // idItem
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // idDiary
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // tag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TagEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdItem(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdDiary(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTag(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TagEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TagEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TagEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
